---

- hosts: test_instances
  become: yes
  gather_facts: no
  tasks:

    - name: Ensure python requirements are installed
      raw: dnf -y install python3-dnf

- hosts: test_instances
  vars_files:
    - vars.yml
  become: yes
  roles:
    - osbuild
