---

- name: Enable fastestmirror on Fedora
  ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: fastestmirror
    value: "1"
  when:
    - ansible_distribution == 'Fedora'

- name: Ensure all packages are updated
  package:
    name: "*"
    state: latest
  register: package_updates
  until: package_updates is success
  retries: 5

- name: Install required packages
  package:
    name: "{{ required_packages }}"
  register: package_install
  until: package_install is success
  retries: 5

- name: Clone osbuild-composer from GitHub
  git:
    repo: https://github.com/osbuild/osbuild-composer
    dest: /opt/osbuild-composer
    version: "{{ osbuild_composer_branch }}"
    force: yes
    clone: yes
    update: yes
    track_submodules: no
  register: git_composer

- name: Install requirements for building osbuild-composer
  command: dnf -y builddep golang-github-osbuild-composer.spec
  args:
    chdir: /opt/osbuild-composer
    warn: no
  register: composer_builddep
  until: composer_builddep is success
  retries: 5

- name: Install requirements for building osbuild
  command: dnf -y builddep osbuild.spec
  args:
    chdir: /opt/osbuild
    warn: no
  register: osbuild_builddep
  until: osbuild_builddep is success
  retries: 5

- name: Build osbuild-composer RPMs
  shell: make rpm
  args:
    chdir: /opt/osbuild-composer
  register: rpm_osbuild_composer
  when:
    - git_composer is changed or force_build

- name: Build osbuild RPMs
  shell: make rpm
  args:
    chdir: /opt/osbuild-composer/osbuild
  register: rpm_osbuild
  when:
    - git_composer is changed or force_build

- name: Get a list of RPMs build for osbuild-composer
  command: "find /opt/osbuild-composer/output -name '*.rpm'"
  register: composer_packages
  when:
    - rpm_osbuild_composer is changed

- name: Get a list of RPMs build for osbuild-composer
  command: "find /opt/osbuild-composer/osbuild/output -name '*.rpm'"
  register: osbuild_packages
  when:
    - rpm_osbuild is changed

- name: Install RPMs
  package:
    name: "{{ composer_packages.stdout_lines + osbuild_packages.stdout_lines }}"
    state: latest
  when:
    - rpm_osbuild_composer is changed or rpm_osbuild is changed
