---

- include_tasks: install.yml

- name: Enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - cockpit.socket
    - osbuild-composer.socket

# composer-cli seems to exit with a return code of 1 when everything is okay.
- name: Test composer-cli
  command: composer-cli status show
  register: composer_cli_test
  failed_when:
    - '"API server status" not in composer_cli_test.stdout'

- name: Show output
  debug:
    var: composer_cli_test.stdout

- name: Run composer tests
  shell: /usr/libexec/tests/osbuild-composer/osbuild-tests
  register: composer_tests
  async: 1200
  poll: 0

- name: Wait for composer tests to finish
  async_status:
    jid: "{{ composer_tests.ansible_job_id }}"
  register: job_result
  until: job_result is finished
  retries: 300
  delay: 15

- name: Show output
  debug:
    var: composer_cli_test.stdout
