---

- name: Set a password for the default user
  user:
    name: "{{ ansible_ssh_user }}"
    password: "{{ password_hashes[ansible_ssh_user] }}"
    update_password: always

- name: Install ssh keys
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ item }}"
  loop: "{{ valid_ssh_keys }}"
  loop_control:
    label: "{{ item.split(' ') | last }}"

- import_tasks: install.yml

- import_tasks: test_api_server.yml

- import_tasks: test_integration.yml
  when: run_integration_tests | bool
