---

- name: Install ssh keys
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ item }}"
  loop: "{{ valid_ssh_keys }}"
  loop_control:
    label: "{{ item.split(' ') | last }}"

- include_tasks: install.yml

- name: Enable services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - cockpit.socket
    - osbuild-composer.socket

# composer-cli seems to exit with a return code of 1 when everything is okay.
- name: Test composer-cli
  command: composer-cli status show
  register: composer_cli_test
  failed_when:
    - '"API server status" not in composer_cli_test.stdout'

- name: Show output
  debug:
    var: composer_cli_test.stdout

- name: Run composer tests
  shell: /usr/libexec/tests/osbuild-composer/osbuild-tests
  register: composer_tests
  async: 1200
  poll: 0
  no_log: yes

- name: Wait for composer tests to finish
  async_status:
    jid: "{{ composer_tests.ansible_job_id }}"
  register: job_result
  until: job_result is finished
  retries: 300
  delay: 15
  no_log: yes

- name: Write composer stdout to file
  copy:
    dest: /tmp/composer_tests_stdout.txt
    content: "{{ composer_tests.stdout }}"

- name: Write composer stderr to file
  copy:
    dest: /tmp/composer_tests_stderr.txt
    content: "{{ composer_tests.stderr }}"

- name: Fetch composer test log files
  fetch:
    src: "/tmp/composer_tests_{{ item }}.txt"
    dest: "{{ CI_PROJECT_DIR }}/composer_tests_{{ item }}.txt"
  loop:
    - stdout
    - stderr

- name: Check for successful test run
  fail:
    msg: "Integration tests failed. Check the logs for more details."
  when:
    - composer_tests is failed
